### request for a Name 

GET http://localhost:3000/acquireName

### request for a place
GET  http://localhost:3000/acquirePlace

### request for a skill
GET  http://localhost:3000/acquireSkill